// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCare.Api.Data;
using PetCare.Api.Model;

#nullable disable

namespace PetCare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419191958_RemoveLegacyAppUserFields")]
    partial class RemoveLegacyAppUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pet_sex", new[] { "male", "female", "unknown" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetCare.Api.Model.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token_hash");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.BreedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Name")
                        .IsUnique();

                    b.ToTable("breeds", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ChatMessageModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "CreatedAt");

                    b.ToTable("chat_messages", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ChatSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chat_sessions", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ConsultationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("details");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VetPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("vet_place_id");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.HasIndex("VetPlaceId");

                    b.ToTable("consultations", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostAttachmentModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ForumPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_post_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ForumPostId");

                    b.ToTable("forum_post_attachments", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostBookmarkModel", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ForumPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_post_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ForumPostId");

                    b.HasIndex("ForumPostId");

                    b.ToTable("forum_post_bookmarks", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAReply")
                        .HasColumnType("boolean")
                        .HasColumnName("is_a_reply");

                    b.Property<Guid?>("ReplyingToPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("replying_to_post");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReplyingToPostId");

                    b.HasIndex("UserId");

                    b.ToTable("forum_posts", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.IllnessRecordModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CuredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cured_date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DiagnosisDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("diagnosis_date");

                    b.Property<string>("IllnessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("illness_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PetId", "Status");

                    b.ToTable("illness_records", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.MedicationRecordModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dosage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dosage");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("FrequencyInDays")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_in_days");

                    b.Property<long>("IllnessId")
                        .HasColumnType("bigint")
                        .HasColumnName("illness_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_name");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_enabled");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<List<string>>("Times")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("times");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReminderEnabled");

                    b.HasIndex("IllnessId", "IsActive");

                    b.ToTable("medication_records", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.PetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<int?>("BreedId")
                        .HasColumnType("integer")
                        .HasColumnName("breed_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("Neutered")
                        .HasColumnType("boolean")
                        .HasColumnName("neutered");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<PetSex>("Sex")
                        .HasColumnType("pet_sex")
                        .HasColumnName("sex");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("pets", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.PetPlaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("photo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("City", "Country");

                    b.ToTable("pet_places", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.SpeciesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("species", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.VaccineRecordModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DateAdministered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_administered");

                    b.Property<DateTimeOffset?>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vaccine_name");

                    b.Property<string>("Veterinarian")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("veterinarian");

                    b.HasKey("Id");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("PetId", "Status");

                    b.ToTable("vaccine_records", "public");
                });

            modelBuilder.Entity("PetCare.Api.Model.BreedModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.SpeciesModel", "Species")
                        .WithMany("Breeds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PetCare.Api.Model.ChatMessageModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.ChatSessionModel", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("PetCare.Api.Model.ChatSessionModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.AppUser", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetCare.Api.Model.ConsultationModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.PetModel", "Pet")
                        .WithMany("Consultations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Api.Model.AppUser", "User")
                        .WithMany("Consultations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Api.Model.PetPlaceModel", "VetPlace")
                        .WithMany("Consultations")
                        .HasForeignKey("VetPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pet");

                    b.Navigation("User");

                    b.Navigation("VetPlace");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostAttachmentModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.ForumPostModel", "ForumPost")
                        .WithMany("Attachments")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumPost");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostBookmarkModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.ForumPostModel", "ForumPost")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Api.Model.AppUser", "User")
                        .WithMany("BookmarkedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.ForumPostModel", "ReplyingToPost")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyingToPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PetCare.Api.Model.AppUser", "User")
                        .WithMany("ForumPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplyingToPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetCare.Api.Model.IllnessRecordModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.PetModel", "Pet")
                        .WithMany("IllnessRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Api.Model.MedicationRecordModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.IllnessRecordModel", "Illness")
                        .WithMany("Medications")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Illness");
                });

            modelBuilder.Entity("PetCare.Api.Model.PetModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.BreedModel", "Breed")
                        .WithMany("Pets")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PetCare.Api.Model.SpeciesModel", "Species")
                        .WithMany("Pets")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCare.Api.Model.AppUser", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetCare.Api.Model.VaccineRecordModel", b =>
                {
                    b.HasOne("PetCare.Api.Model.PetModel", "Pet")
                        .WithMany("VaccineRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Api.Model.AppUser", b =>
                {
                    b.Navigation("BookmarkedPosts");

                    b.Navigation("Chats");

                    b.Navigation("Consultations");

                    b.Navigation("ForumPosts");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Api.Model.BreedModel", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Api.Model.ChatSessionModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PetCare.Api.Model.ForumPostModel", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Bookmarks");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("PetCare.Api.Model.IllnessRecordModel", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PetCare.Api.Model.PetModel", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("IllnessRecords");

                    b.Navigation("VaccineRecords");
                });

            modelBuilder.Entity("PetCare.Api.Model.PetPlaceModel", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("PetCare.Api.Model.SpeciesModel", b =>
                {
                    b.Navigation("Breeds");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
