-- PetCare backend schema for PostgreSQL
-- Run with:
--   psql -h 127.0.0.1 -U petapp -d petapp -f PetCare.Api/PetCare.Api/sql/create_schema.sql

BEGIN;

CREATE SCHEMA IF NOT EXISTS public;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'pet_sex'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.pet_sex AS ENUM ('male', 'female', 'unknown');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.species (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL,
    name character varying(200),
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(320) NOT NULL,
    phone_number character varying(50) NOT NULL,
    password_hash text NOT NULL,
    avatar_url character varying(1024),
    description character varying(1000),
    created_at timestamp with time zone NOT NULL,
    last_login timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.pet_places (
    id uuid PRIMARY KEY,
    name character varying(200) NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(320) NOT NULL,
    photo character varying(1024),
    description character varying(2000),
    address_line1 character varying(200) NOT NULL,
    address_line2 character varying(200),
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    status character varying(30) NOT NULL,
    type character varying(30) NOT NULL,
    lat numeric(9,6),
    lon numeric(9,6),
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.breeds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id integer NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT fk_breeds_species_species_id
        FOREIGN KEY (species_id)
        REFERENCES public.species (id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT fk_chat_sessions_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.forum_posts (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL,
    content character varying(5000) NOT NULL,
    is_a_reply boolean NOT NULL,
    replying_to_post uuid,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT fk_forum_posts_forum_posts_replying_to_post
        FOREIGN KEY (replying_to_post)
        REFERENCES public.forum_posts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_forum_posts_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.pets (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL,
    name character varying(120) NOT NULL,
    species_id integer NOT NULL,
    breed_id integer,
    sex public.pet_sex NOT NULL,
    birth_date timestamp with time zone,
    weight_kg numeric(5,2),
    color character varying(30) NOT NULL,
    neutered boolean NOT NULL,
    avatar_url character varying(1024),
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_pets_breeds_breed_id
        FOREIGN KEY (breed_id)
        REFERENCES public.breeds (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_pets_species_species_id
        FOREIGN KEY (species_id)
        REFERENCES public.species (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_pets_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_session_id uuid NOT NULL,
    role character varying(10) NOT NULL,
    content character varying(5000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_chat_messages_chat_sessions_chat_session_id
        FOREIGN KEY (chat_session_id)
        REFERENCES public.chat_sessions (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.forum_post_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forum_post_id uuid NOT NULL,
    url character varying(1024) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_forum_post_attachments_forum_posts_forum_post_id
        FOREIGN KEY (forum_post_id)
        REFERENCES public.forum_posts (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.forum_post_bookmarks (
    user_id bigint NOT NULL,
    forum_post_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_forum_post_bookmarks PRIMARY KEY (user_id, forum_post_id),
    CONSTRAINT fk_forum_post_bookmarks_forum_posts_forum_post_id
        FOREIGN KEY (forum_post_id)
        REFERENCES public.forum_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_post_bookmarks_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.consultations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    pet_id uuid NOT NULL,
    vet_place_id uuid,
    date timestamp with time zone NOT NULL,
    details character varying(3000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT fk_consultations_pet_places_vet_place_id
        FOREIGN KEY (vet_place_id)
        REFERENCES public.pet_places (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_consultations_pets_pet_id
        FOREIGN KEY (pet_id)
        REFERENCES public.pets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_consultations_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.illness_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id uuid NOT NULL,
    illness_name character varying(200) NOT NULL,
    diagnosis_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    description character varying(2000),
    notes character varying(2000),
    cured_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_illness_records_pets_pet_id
        FOREIGN KEY (pet_id)
        REFERENCES public.pets (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.vaccine_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id uuid NOT NULL,
    vaccine_name character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    date_administered timestamp with time zone,
    next_due_date timestamp with time zone,
    notes character varying(2000),
    veterinarian character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_vaccine_records_pets_pet_id
        FOREIGN KEY (pet_id)
        REFERENCES public.pets (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.medication_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    illness_id bigint NOT NULL,
    medication_name character varying(200) NOT NULL,
    dosage character varying(200),
    instructions character varying(2000),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    frequency_in_days integer NOT NULL,
    times text[] NOT NULL,
    reminder_enabled boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_medication_records_illness_records_illness_id
        FOREIGN KEY (illness_id)
        REFERENCES public.illness_records (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_species_code
    ON public.species (code);

CREATE UNIQUE INDEX IF NOT EXISTS ix_species_name
    ON public.species (name);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email
    ON public.users (email);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username
    ON public.users (username);

CREATE UNIQUE INDEX IF NOT EXISTS ix_breeds_species_id_name
    ON public.breeds (species_id, name);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_id
    ON public.chat_sessions (user_id);

CREATE INDEX IF NOT EXISTS ix_chat_messages_chat_session_id_created_at
    ON public.chat_messages (chat_session_id, created_at);

CREATE INDEX IF NOT EXISTS ix_forum_posts_user_id
    ON public.forum_posts (user_id);

CREATE INDEX IF NOT EXISTS ix_forum_posts_replying_to_post
    ON public.forum_posts (replying_to_post);

CREATE INDEX IF NOT EXISTS ix_forum_posts_created_at
    ON public.forum_posts (created_at);

CREATE INDEX IF NOT EXISTS ix_forum_post_attachments_forum_post_id
    ON public.forum_post_attachments (forum_post_id);

CREATE INDEX IF NOT EXISTS ix_forum_post_bookmarks_forum_post_id
    ON public.forum_post_bookmarks (forum_post_id);

CREATE INDEX IF NOT EXISTS ix_pet_places_type
    ON public.pet_places (type);

CREATE INDEX IF NOT EXISTS ix_pet_places_status
    ON public.pet_places (status);

CREATE INDEX IF NOT EXISTS ix_pet_places_city_country
    ON public.pet_places (city, country);

CREATE INDEX IF NOT EXISTS ix_pets_breed_id
    ON public.pets (breed_id);

CREATE INDEX IF NOT EXISTS ix_pets_species_id
    ON public.pets (species_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_pets_user_id_name
    ON public.pets (user_id, name);

CREATE INDEX IF NOT EXISTS ix_consultations_date
    ON public.consultations (date);

CREATE INDEX IF NOT EXISTS ix_consultations_pet_id
    ON public.consultations (pet_id);

CREATE INDEX IF NOT EXISTS ix_consultations_user_id
    ON public.consultations (user_id);

CREATE INDEX IF NOT EXISTS ix_consultations_vet_place_id
    ON public.consultations (vet_place_id);

CREATE INDEX IF NOT EXISTS ix_illness_records_pet_id_status
    ON public.illness_records (pet_id, status);

CREATE INDEX IF NOT EXISTS ix_vaccine_records_next_due_date
    ON public.vaccine_records (next_due_date);

CREATE INDEX IF NOT EXISTS ix_vaccine_records_pet_id_status
    ON public.vaccine_records (pet_id, status);

CREATE INDEX IF NOT EXISTS ix_medication_records_illness_id_is_active
    ON public.medication_records (illness_id, is_active);

CREATE INDEX IF NOT EXISTS ix_medication_records_reminder_enabled
    ON public.medication_records (reminder_enabled);

COMMIT;
