CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TYPE pet_sex AS ENUM ('male', 'female', 'unknown');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.pet_places (
        id uuid NOT NULL,
        name character varying(200) NOT NULL,
        phone character varying(50) NOT NULL,
        email character varying(320) NOT NULL,
        photo character varying(1024),
        description character varying(2000),
        address_line1 character varying(200) NOT NULL,
        address_line2 character varying(200),
        city character varying(100) NOT NULL,
        country character varying(100) NOT NULL,
        status character varying(30) NOT NULL,
        type character varying(30) NOT NULL,
        lat numeric(9,6),
        lon numeric(9,6),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pet_places" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.species (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(50) NOT NULL,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_species" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.users (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        username character varying(100) NOT NULL,
        name character varying(200),
        first_name character varying(100) NOT NULL,
        last_name character varying(100) NOT NULL,
        email character varying(320) NOT NULL,
        phone_number character varying(50) NOT NULL,
        password_hash text NOT NULL,
        avatar_url character varying(1024),
        description character varying(1000),
        created_at timestamp with time zone NOT NULL,
        last_login timestamp with time zone,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.breeds (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        species_id integer NOT NULL,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_breeds" PRIMARY KEY (id),
        CONSTRAINT "FK_breeds_species_species_id" FOREIGN KEY (species_id) REFERENCES public.species (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.chat_sessions (
        id uuid NOT NULL,
        user_id bigint NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_chat_sessions" PRIMARY KEY (id),
        CONSTRAINT "FK_chat_sessions_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.forum_posts (
        id uuid NOT NULL,
        user_id bigint NOT NULL,
        content character varying(5000) NOT NULL,
        is_a_reply boolean NOT NULL,
        replying_to_post uuid,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_forum_posts" PRIMARY KEY (id),
        CONSTRAINT "FK_forum_posts_forum_posts_replying_to_post" FOREIGN KEY (replying_to_post) REFERENCES public.forum_posts (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_forum_posts_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.pets (
        id uuid NOT NULL,
        user_id bigint NOT NULL,
        name character varying(120) NOT NULL,
        species_id integer NOT NULL,
        breed_id integer,
        sex pet_sex NOT NULL,
        birth_date timestamp with time zone,
        weight_kg numeric(5,2),
        color character varying(30) NOT NULL,
        neutered boolean NOT NULL,
        avatar_url character varying(1024),
        notes character varying(2000),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pets" PRIMARY KEY (id),
        CONSTRAINT "FK_pets_breeds_breed_id" FOREIGN KEY (breed_id) REFERENCES public.breeds (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_pets_species_species_id" FOREIGN KEY (species_id) REFERENCES public.species (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_pets_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.chat_messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        chat_session_id uuid NOT NULL,
        role character varying(10) NOT NULL,
        content character varying(5000) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_chat_messages" PRIMARY KEY (id),
        CONSTRAINT "FK_chat_messages_chat_sessions_chat_session_id" FOREIGN KEY (chat_session_id) REFERENCES public.chat_sessions (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.forum_post_attachments (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        forum_post_id uuid NOT NULL,
        url character varying(1024) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_forum_post_attachments" PRIMARY KEY (id),
        CONSTRAINT "FK_forum_post_attachments_forum_posts_forum_post_id" FOREIGN KEY (forum_post_id) REFERENCES public.forum_posts (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.forum_post_bookmarks (
        user_id bigint NOT NULL,
        forum_post_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_forum_post_bookmarks" PRIMARY KEY (user_id, forum_post_id),
        CONSTRAINT "FK_forum_post_bookmarks_forum_posts_forum_post_id" FOREIGN KEY (forum_post_id) REFERENCES public.forum_posts (id) ON DELETE CASCADE,
        CONSTRAINT "FK_forum_post_bookmarks_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.consultations (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        pet_id uuid NOT NULL,
        vet_place_id uuid,
        date timestamp with time zone NOT NULL,
        details character varying(3000) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_consultations" PRIMARY KEY (id),
        CONSTRAINT "FK_consultations_pet_places_vet_place_id" FOREIGN KEY (vet_place_id) REFERENCES public.pet_places (id) ON DELETE SET NULL,
        CONSTRAINT "FK_consultations_pets_pet_id" FOREIGN KEY (pet_id) REFERENCES public.pets (id) ON DELETE CASCADE,
        CONSTRAINT "FK_consultations_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.illness_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pet_id uuid NOT NULL,
        illness_name character varying(200) NOT NULL,
        diagnosis_date timestamp with time zone NOT NULL,
        status character varying(20) NOT NULL,
        description character varying(2000),
        notes character varying(2000),
        cured_date timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_illness_records" PRIMARY KEY (id),
        CONSTRAINT "FK_illness_records_pets_pet_id" FOREIGN KEY (pet_id) REFERENCES public.pets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.vaccine_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pet_id uuid NOT NULL,
        vaccine_name character varying(200) NOT NULL,
        status character varying(20) NOT NULL,
        date_administered timestamp with time zone,
        next_due_date timestamp with time zone,
        notes character varying(2000),
        veterinarian character varying(200),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_vaccine_records" PRIMARY KEY (id),
        CONSTRAINT "FK_vaccine_records_pets_pet_id" FOREIGN KEY (pet_id) REFERENCES public.pets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE TABLE public.medication_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        illness_id bigint NOT NULL,
        medication_name character varying(200) NOT NULL,
        dosage character varying(200),
        instructions character varying(2000),
        start_date timestamp with time zone NOT NULL,
        end_date timestamp with time zone,
        frequency_in_days integer NOT NULL,
        times text[] NOT NULL,
        reminder_enabled boolean NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_medication_records" PRIMARY KEY (id),
        CONSTRAINT "FK_medication_records_illness_records_illness_id" FOREIGN KEY (illness_id) REFERENCES public.illness_records (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_breeds_species_id_name" ON public.breeds (species_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_chat_messages_chat_session_id_created_at" ON public.chat_messages (chat_session_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_chat_sessions_user_id" ON public.chat_sessions (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_consultations_date" ON public.consultations (date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_consultations_pet_id" ON public.consultations (pet_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_consultations_user_id" ON public.consultations (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_consultations_vet_place_id" ON public.consultations (vet_place_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_forum_post_attachments_forum_post_id" ON public.forum_post_attachments (forum_post_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_forum_post_bookmarks_forum_post_id" ON public.forum_post_bookmarks (forum_post_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_forum_posts_created_at" ON public.forum_posts (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_forum_posts_replying_to_post" ON public.forum_posts (replying_to_post);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_forum_posts_user_id" ON public.forum_posts (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_illness_records_pet_id_status" ON public.illness_records (pet_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_medication_records_illness_id_is_active" ON public.medication_records (illness_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_medication_records_reminder_enabled" ON public.medication_records (reminder_enabled);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_pet_places_city_country" ON public.pet_places (city, country);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_pet_places_status" ON public.pet_places (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_pet_places_type" ON public.pet_places (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_pets_breed_id" ON public.pets (breed_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_pets_species_id" ON public.pets (species_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_pets_user_id_name" ON public.pets (user_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_species_code" ON public.species (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_species_name" ON public.species (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON public.users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE UNIQUE INDEX "IX_users_username" ON public.users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_vaccine_records_next_due_date" ON public.vaccine_records (next_due_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    CREATE INDEX "IX_vaccine_records_pet_id_status" ON public.vaccine_records (pet_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405175850_AlignFrontendDomainModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260405175850_AlignFrontendDomainModel', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418021354_AddEmailVerification') THEN
    ALTER TABLE public.users ADD email_verification_token_expires_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418021354_AddEmailVerification') THEN
    ALTER TABLE public.users ADD email_verification_token_hash text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418021354_AddEmailVerification') THEN
    ALTER TABLE public.users ADD email_verified boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418021354_AddEmailVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418021354_AddEmailVerification', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419191958_RemoveLegacyAppUserFields') THEN
    ALTER TABLE public.users DROP COLUMN name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419191958_RemoveLegacyAppUserFields') THEN
    ALTER TABLE public.users DROP COLUMN phone_number;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419191958_RemoveLegacyAppUserFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419191958_RemoveLegacyAppUserFields', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419202857_AddPetPlaceWeeklySchedules') THEN
    CREATE TABLE public.pet_place_schedules (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pet_place_id uuid NOT NULL,
        day_of_week character varying(20) NOT NULL,
        is_closed boolean NOT NULL,
        open_time time without time zone,
        close_time time without time zone,
        break_start_time time without time zone,
        break_end_time time without time zone,
        CONSTRAINT "PK_pet_place_schedules" PRIMARY KEY (id),
        CONSTRAINT "FK_pet_place_schedules_pet_places_pet_place_id" FOREIGN KEY (pet_place_id) REFERENCES public.pet_places (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419202857_AddPetPlaceWeeklySchedules') THEN
    CREATE UNIQUE INDEX "IX_pet_place_schedules_pet_place_id_day_of_week" ON public.pet_place_schedules (pet_place_id, day_of_week);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419202857_AddPetPlaceWeeklySchedules') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419202857_AddPetPlaceWeeklySchedules', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419211906_AddForumPostLikes') THEN
    CREATE TABLE public.forum_post_likes (
        user_id bigint NOT NULL,
        forum_post_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_forum_post_likes" PRIMARY KEY (user_id, forum_post_id),
        CONSTRAINT "FK_forum_post_likes_forum_posts_forum_post_id" FOREIGN KEY (forum_post_id) REFERENCES public.forum_posts (id) ON DELETE CASCADE,
        CONSTRAINT "FK_forum_post_likes_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419211906_AddForumPostLikes') THEN
    CREATE INDEX "IX_forum_post_likes_forum_post_id" ON public.forum_post_likes (forum_post_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419211906_AddForumPostLikes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419211906_AddForumPostLikes', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    ALTER TABLE public.users ADD ban_reason character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    ALTER TABLE public.users ADD banned_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    ALTER TABLE public.users ADD is_banned boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    CREATE TABLE public.admin_users (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        username character varying(100) NOT NULL,
        first_name character varying(100) NOT NULL,
        last_name character varying(100) NOT NULL,
        email character varying(320) NOT NULL,
        password_hash text NOT NULL,
        role character varying(20) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        last_login timestamp with time zone,
        CONSTRAINT "PK_admin_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    CREATE UNIQUE INDEX "IX_admin_users_email" ON public.admin_users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    CREATE UNIQUE INDEX "IX_admin_users_username" ON public.admin_users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421020442_AddAdminSystemAndUserModeration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260421020442_AddAdminSystemAndUserModeration', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE TABLE public.admin_action_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        admin_user_id bigint NOT NULL,
        action_type character varying(100) NOT NULL,
        target_type character varying(100) NOT NULL,
        target_id character varying(100) NOT NULL,
        description character varying(1000) NOT NULL,
        reason character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_admin_action_logs" PRIMARY KEY (id),
        CONSTRAINT "FK_admin_action_logs_admin_users_admin_user_id" FOREIGN KEY (admin_user_id) REFERENCES public.admin_users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_action_type" ON public.admin_action_logs (action_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_admin_user_id" ON public.admin_action_logs (admin_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_admin_user_id_created_at" ON public.admin_action_logs (admin_user_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_created_at" ON public.admin_action_logs (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_target_id" ON public.admin_action_logs (target_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    CREATE INDEX "IX_admin_action_logs_target_type" ON public.admin_action_logs (target_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421034954_AddAdminActionLogs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260421034954_AddAdminActionLogs', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    CREATE TABLE public.pet_place_reviews (
        id uuid NOT NULL,
        place_id uuid NOT NULL,
        user_id bigint NOT NULL,
        rating integer NOT NULL,
        comment character varying(2000),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_pet_place_reviews" PRIMARY KEY (id),
        CONSTRAINT "CK_pet_place_reviews_rating_range" CHECK (rating >= 1 AND rating <= 5),
        CONSTRAINT "FK_pet_place_reviews_pet_places_place_id" FOREIGN KEY (place_id) REFERENCES public.pet_places (id) ON DELETE CASCADE,
        CONSTRAINT "FK_pet_place_reviews_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    CREATE INDEX "IX_pet_place_reviews_created_at" ON public.pet_place_reviews (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    CREATE INDEX "IX_pet_place_reviews_place_id" ON public.pet_place_reviews (place_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    CREATE UNIQUE INDEX "IX_pet_place_reviews_place_id_user_id" ON public.pet_place_reviews (place_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    CREATE INDEX "IX_pet_place_reviews_user_id" ON public.pet_place_reviews (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422154558_AddPetPlaceReviews') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260422154558_AddPetPlaceReviews', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE TABLE public.reports (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        reporter_user_id bigint NOT NULL,
        target_type character varying(30) NOT NULL,
        target_id character varying(100) NOT NULL,
        reason_type character varying(40) NOT NULL,
        description character varying(2000),
        status character varying(20) NOT NULL,
        reviewed_by_admin_id bigint,
        reviewed_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_reports" PRIMARY KEY (id),
        CONSTRAINT "FK_reports_admin_users_reviewed_by_admin_id" FOREIGN KEY (reviewed_by_admin_id) REFERENCES public.admin_users (id) ON DELETE SET NULL,
        CONSTRAINT "FK_reports_users_reporter_user_id" FOREIGN KEY (reporter_user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_created_at" ON public.reports (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_reason_type" ON public.reports (reason_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_reporter_user_id" ON public.reports (reporter_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE UNIQUE INDEX "IX_reports_reporter_user_id_target_type_target_id" ON public.reports (reporter_user_id, target_type, target_id) WHERE "status" = 'Pending';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_reviewed_by_admin_id" ON public.reports (reviewed_by_admin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_status" ON public.reports (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_target_type" ON public.reports (target_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_target_type_target_id" ON public.reports (target_type, target_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    CREATE INDEX "IX_reports_target_type_target_id_status" ON public.reports (target_type, target_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422163111_AddReportsSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260422163111_AddReportsSystem', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    ALTER TABLE public.users ADD is_approved_place_owner boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    ALTER TABLE public.pet_places ADD owner_user_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE TABLE public.place_owner_applications (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        business_name character varying(200) NOT NULL,
        phone character varying(50) NOT NULL,
        email character varying(320) NOT NULL,
        description character varying(2000),
        address_line1 character varying(200) NOT NULL,
        address_line2 character varying(200),
        city character varying(100) NOT NULL,
        country character varying(100) NOT NULL,
        requested_place_type character varying(30) NOT NULL,
        status character varying(20) NOT NULL,
        rejection_reason character varying(1000),
        admin_notes character varying(1000),
        reviewed_by_admin_id bigint,
        reviewed_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_place_owner_applications" PRIMARY KEY (id),
        CONSTRAINT "FK_place_owner_applications_admin_users_reviewed_by_admin_id" FOREIGN KEY (reviewed_by_admin_id) REFERENCES public.admin_users (id) ON DELETE SET NULL,
        CONSTRAINT "FK_place_owner_applications_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_pet_places_owner_user_id" ON public.pet_places (owner_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_place_owner_applications_created_at" ON public.place_owner_applications (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_place_owner_applications_requested_place_type" ON public.place_owner_applications (requested_place_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_place_owner_applications_reviewed_by_admin_id" ON public.place_owner_applications (reviewed_by_admin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_place_owner_applications_status" ON public.place_owner_applications (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE INDEX "IX_place_owner_applications_user_id" ON public.place_owner_applications (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    CREATE UNIQUE INDEX "IX_place_owner_applications_user_id_status" ON public.place_owner_applications (user_id, status) WHERE "status" = 'Pending';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    ALTER TABLE public.pet_places ADD CONSTRAINT "FK_pet_places_users_owner_user_id" FOREIGN KEY (owner_user_id) REFERENCES public.users (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422192644_AddPlaceOwnerApplicationFlow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260422192644_AddPlaceOwnerApplicationFlow', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422225430_RemoveChatbotInfrastructure') THEN
    DROP TABLE public.chat_messages;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422225430_RemoveChatbotInfrastructure') THEN
    DROP TABLE public.chat_sessions;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422225430_RemoveChatbotInfrastructure') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260422225430_RemoveChatbotInfrastructure', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    ALTER TABLE public.users ADD email_change_code_expires_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    ALTER TABLE public.users ADD email_change_code_hash text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    ALTER TABLE public.users ADD password_reset_code_expires_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    ALTER TABLE public.users ADD password_reset_code_hash text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    ALTER TABLE public.users ADD pending_new_email character varying(320);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426012322_AddUserAccountSecurityFlows') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426012322_AddUserAccountSecurityFlows', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE TABLE public.pet_place_images (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pet_place_id uuid NOT NULL,
        url character varying(1024) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pet_place_images" PRIMARY KEY (id),
        CONSTRAINT "FK_pet_place_images_pet_places_pet_place_id" FOREIGN KEY (pet_place_id) REFERENCES public.pet_places (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE TABLE public.place_owner_application_images (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        place_owner_application_id bigint NOT NULL,
        url character varying(1024) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_place_owner_application_images" PRIMARY KEY (id),
        CONSTRAINT "FK_place_owner_application_images_place_owner_applications_pla~" FOREIGN KEY (place_owner_application_id) REFERENCES public.place_owner_applications (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE INDEX "IX_pet_place_images_pet_place_id" ON public.pet_place_images (pet_place_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE INDEX "IX_pet_place_images_pet_place_id_created_at" ON public.pet_place_images (pet_place_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE INDEX "IX_place_owner_application_images_place_owner_application_id" ON public.place_owner_application_images (place_owner_application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    CREATE INDEX "IX_place_owner_application_images_place_owner_application_id_c~" ON public.place_owner_application_images (place_owner_application_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426030355_AddPlaceAndApplicationImages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426030355_AddPlaceAndApplicationImages', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426050523_AddForumPostMediaAttachments') THEN
    ALTER TABLE public.forum_post_attachments ADD file_size_bytes bigint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426050523_AddForumPostMediaAttachments') THEN
    ALTER TABLE public.forum_post_attachments ADD media_type character varying(20) NOT NULL DEFAULT 'Image';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426050523_AddForumPostMediaAttachments') THEN
    UPDATE public.forum_post_attachments
    SET media_type = CASE
        WHEN lower(split_part(url, '?', 1)) LIKE '%.mp4' THEN 'Video'
        WHEN lower(split_part(url, '?', 1)) LIKE '%.webm' THEN 'Video'
        ELSE 'Image'
    END;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426050523_AddForumPostMediaAttachments') THEN
    CREATE INDEX "IX_forum_post_attachments_forum_post_id_created_at" ON public.forum_post_attachments (forum_post_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426050523_AddForumPostMediaAttachments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426050523_AddForumPostMediaAttachments', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426054756_AddUserBlocking') THEN
    CREATE TABLE public.user_blocks (
        blocker_user_id bigint NOT NULL,
        blocked_user_id bigint NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_user_blocks" PRIMARY KEY (blocker_user_id, blocked_user_id),
        CONSTRAINT "FK_user_blocks_users_blocked_user_id" FOREIGN KEY (blocked_user_id) REFERENCES public.users (id) ON DELETE CASCADE,
        CONSTRAINT "FK_user_blocks_users_blocker_user_id" FOREIGN KEY (blocker_user_id) REFERENCES public.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426054756_AddUserBlocking') THEN
    CREATE INDEX "IX_user_blocks_blocked_user_id" ON public.user_blocks (blocked_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426054756_AddUserBlocking') THEN
    CREATE INDEX "IX_user_blocks_created_at" ON public.user_blocks (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426054756_AddUserBlocking') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426054756_AddUserBlocking', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD admin_moderation_notes character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD ai_moderation_confidence numeric(5,4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD ai_moderation_label character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD ai_moderation_reason character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD moderated_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD moderation_status character varying(30) NOT NULL DEFAULT 'None';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD reviewed_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD reviewed_by_admin_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    CREATE INDEX "IX_forum_posts_ai_moderation_label" ON public.forum_posts (ai_moderation_label);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    CREATE INDEX "IX_forum_posts_moderated_at" ON public.forum_posts (moderated_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    CREATE INDEX "IX_forum_posts_moderation_status" ON public.forum_posts (moderation_status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    CREATE INDEX "IX_forum_posts_moderation_status_created_at" ON public.forum_posts (moderation_status, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    CREATE INDEX "IX_forum_posts_reviewed_by_admin_id" ON public.forum_posts (reviewed_by_admin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    ALTER TABLE public.forum_posts ADD CONSTRAINT "FK_forum_posts_admin_users_reviewed_by_admin_id" FOREIGN KEY (reviewed_by_admin_id) REFERENCES public.admin_users (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426214622_AddForumTextAiModeration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426214622_AddForumTextAiModeration', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426222554_AddForumFinalModerationLabel') THEN
    ALTER TABLE public.forum_posts ADD final_moderation_label character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426222554_AddForumFinalModerationLabel') THEN
    CREATE INDEX "IX_forum_posts_final_moderation_label" ON public.forum_posts (final_moderation_label);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426222554_AddForumFinalModerationLabel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426222554_AddForumFinalModerationLabel', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'petapp'
    ) THEN
        GRANT USAGE ON SCHEMA public TO petapp;
        GRANT USAGE ON TYPE public.pet_sex TO petapp;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO petapp;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO petapp;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO petapp;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT USAGE, SELECT ON SEQUENCES TO petapp;
    ELSE
        RAISE NOTICE 'Role "petapp" does not exist. Skipping grants.';
    END IF;
END $EF$;
COMMIT;
